spring:
  # default host & port is localhost:6379
  jpa:
    properties:
      hibernate:
        # show formatted sql
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/local_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8'
    username: root
    password: password
